# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  elevateyourintake.com:
    site_hosts:
      - canonical: elevateyourintake.dev
        redirects:
          - www.elevateyourintake.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: andrew.wilhelm@discreteunits.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
